Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideBrackets:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Lint/AmbiguousOperator:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: true

Style/ClassVars:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: inject
    detect: find

Style/Documentation:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19

Metrics/LineLength:
  Max: 458

Metrics/MethodLength:
  Max: 11

Metrics/BlockLength:
  Exclude:
    - "spec/**/*_spec.rb"

Style/Next:
  Enabled: true

Style/PredicateName:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SignalException:
  Enabled: true
  EnforcedStyle: only_raise

Style/RaiseArgs:
  Enabled: false

Style/StringLiterals:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: true

Style/TrailingCommaInArguments:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Style/Lambda:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/AndOr:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.4.1
  Exclude:
    - '**/vendor/**/*'
    - '.bundle/**/*'
